version: '3'
services:
  server:
    build:
      context: .
    command: ['python', '-m', 'app.local_app']
    ports:
      - "9000:9000"
    volumes:
      - ./app:/code/app
      - ./settings:/code/settings
      - ./resources:/code/resources
    environment:
      - PYTHONUNBUFFERED=1
      - LUIS_URL
      - SENTRY_DSN